# helloworld-demo Service  - Edited VSCode
apiVersion: v1
kind: Service
metadata:
  name: svc-my-helloworld-test
  labels:
    whatCat: my-helloworld-test
spec:
  type: NodePort
  ports:
  - nodePort: 32090
    port: 9090
    protocol: TCP
  selector:
    whatCat: my-helloworld-test