# bdpms-mariadb StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-bdpms-mariadb
  namespace: ns-bdpms
spec:
  serviceName: svc-bdpms-mariadb
  replicas: 1
  selector:
    matchLabels:
      whatCat: bdpms-mariadb
  template:
    metadata:
      labels:
        whatCat: bdpms-mariadb
    spec:
      containers:
      - name: ctn-bdpms-mariadb
        image: yaongdocker/bdpms-mariadb:0.2
        imagePullPolicy: Always
        ports:
          - name: dbms-port
            containerPort: 3306
---
# bdpms-mariadb Service
apiVersion: v1
kind: Service
metadata:
  name: svc-bdpms-mariadb
  namespace: ns-bdpms
spec:
  ports:
    - port: 3306
      name: mariadb-port
  clusterIP: None
  selector:
    whatCat: bdpms-mariadb