# bdpms-redmine Deployment - Edited VSCode
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-bdpms-redmine
  namespace: ns-bdpms
  labels:
    whatCat: bdpms-redmine  
spec:
  selector:
    matchLabels:
      whatCat: bdpms-redmine
  replicas: 1
  template:
    metadata:
      labels:
        whatCat: bdpms-redmine
    spec:
      initContainers:
      - name: ctn-bdpms-redmine-init
        command: ["/bin/sh"]
        args: ["-c","sed  -i 's/192.168.55.174/svc-bdpms-mariadb/g'  /usr/src/redmine/config/database.yml "]
        image: yaongdocker/bdpms-redmine:0.1
      containers:
      - name: ctn-bdpms-redmine
        image: yaongdocker/bdpms-redmine:0.1
        ports:
          - name: http-port
            containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        env:
          - name: REDMINE_DB_MYSQL
            value: "svc-bdpms-mariadb"
          - name: REDMINE_DB_PORT
            value: "3306" 
          - name: REDMINE_DB_DATABASE
            value: "redmine" 
          - name: REDMINE_DB_PASSWORD
            value: "admin"                                            
---
# bdpms-redmine Service
apiVersion: v1
kind: Service
metadata:
  name: svc-bdpms-redmine
  namespace: ns-bdpms
spec:
  type: NodePort
  ports:
    - port: 13000
      targetPort: 3000
  selector:
    whatCat: bdpms-redmine