# bdpms-migtool Deployment - Edited VSCode
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-bdpms-migtool
  namespace: ns-bdpms
  labels:
    whatCat: bdpms-migtool  
spec:
  selector:
    matchLabels:
      whatCat: bdpms-migtool
  replicas: 1
  template:
    metadata:
      labels:
        whatCat: bdpms-migtool
    spec:
      containers:
      - name: ctn-bdpms-migtool
        image: yaongdocker/bdpms-migtool:0.1
        ports:
          - name: http-port
            containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
# bdpms-migtool Service
apiVersion: v1
kind: Service
metadata:
  name: svc-bdpms-migtool
  namespace: ns-bdpms
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 18080
  selector:
    whatCat: bdpms-migtool