# bdpms-mariadb StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-bdpms-mariadb
  namespace: ns-bdpms
spec:
  serviceName: svc-bdpms-mariadb
  replicas: 1
  selector:
    matchLabels:
      whatCat: bdpms-mariadb
  template:
    metadata:
      labels:
        whatCat: bdpms-mariadb
    spec:
      initContainers:
      - name: ctn-bdpms-mariadb-init
        command: ['sh', '-c', "mkdir -p  /run/mysqld ; chmod 755 /run/mysqld -R ; ls -laF /run/mysqld"]
        image: yaongdocker/bdpms-mariadb:0.1
        volumeMounts:
          - name: vol-mariadb
            mountPath: /var/lib/mysql
      containers:
      - name: ctn-bdpms-mariadb
        image: yaongdocker/bdpms-mariadb:0.1
        securityContext:
          runAsUser: 1000
          #allowPrivilegeEscalation: false
        ports:
          - name: dbms-port
            containerPort: 3306
        volumeMounts:
          - name: vol-mariadb
            mountPath: /var/lib/mysql          
      volumes:         
        - name: vol-mariadb
          hostPath:
            path: /mnt/hgfs/vmshare/bdpms-data/mysqldata
            type: Directory
---
# bdpms-mariadb Service
apiVersion: v1
kind: Service
metadata:
  name: svc-bdpms-mariadb
  namespace: ns-bdpms
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    whatCat: bdpms-mariadb